name: nid_poule_app
description: Nids de poule tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter map compatible avec ton code actuel
  flutter_map: 3.1.0
  latlong2: 0.8.1

  # Firebase : versions compatibles entre elles
  firebase_core: 2.25.0
  cloud_firestore: 4.9.0
  firebase_storage: 10.4.3

  # File picker
  file_picker: 5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true