name: nid_poule_app
description: Nids de poule tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  file_picker: ^8.1.2
  geolocator: ^13.0.1
  image_picker: ^1.1.2  # Photos/Camera
  camera: ^0.11.0+1     # Camera native

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1  # Icônes

flutter:
  uses-material-design: true
  
  # LAUNCHER ICONS (obligatoire)
  flutter_launcher_icons:
    android: "launcher_icon"
    image_path: "assets/icon.png"  # Créez 1024x1024 PNG

# Permissions auto via plugins