name: nid_poule_app
description: Nid Poule Tracker
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  file_picker: ^10.3.10
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
