name: nid_poule_app
description: Nids de poule tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.8.1
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
